### ISSUE TITLE
Error: Spawn meteor ENOENT

### ISSUE THREAD

**Issue by Radizzt** [CapsuleCat/OfflineMeteorAppExample#1]
I'm not sure if this still works. But I tried it and follow your instruction form the capsule page and I'm getting this error:

```
> meteor-local@1.0.0 build /Users/MAC1/Documents/Richard/Hots Mobile
> node build.js

events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: spawn meteor ENOENT
    at exports._errnoException (util.js:1012:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:182:32)
    at onErrorNT (internal/child_process.js:348:16)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
    at Module.runMain (module.js:577:11)
    at run (bootstrap_node.js:352:7)
    at startup (bootstrap_node.js:144:9)
    at bootstrap_node.js:467:3

npm ERR! Darwin 14.3.0
npm ERR! argv "/Users/MAC1/.nvm/versions/node/v6.3.1/bin/node" "/Users/MAC1/.nvm/versions/node/v6.3.1/bin/npm" "run" "build"
npm ERR! node v6.3.1
npm ERR! npm  v4.3.0
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! meteor-local@1.0.0 build: `node build.js`
npm ERR! Exit status 1
```

Any idea what the issue is?

**Comment by Radizzt** [comment]
Never mind I found the reason was  because the spawn `cwd` property was pointing at a non existent directory
